### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by HaoZeke** [ropensci-review-tools/pkgcheck-action#41]
It seems like the CI is unable to [open the issue](https://github.com/HaoZeke/fastMatMR/actions/runs/6034574563/job/16373217825#step:3:1228) to be appended to anymore. Possibly related to #36 and #25. It seems like taking an environment variable in the workflow would bypass this, the user would just need to ensure the right access.

![image](https://github.com/ropensci-review-tools/pkgcheck-action/assets/4336207/c00197a9-221a-48c2-90d5-e4f61aa766a6)

**Comment by HaoZeke** [comment]
Can be circumvented also by altering the [permissions of the job](https://docs.github.com/en/actions/security-guides/automatic-token-authentication):

```yaml
jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
```
